//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yooocan.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RedisKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RedisKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yooocan.Logic.RedisKeys", typeof(RedisKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to altoCategoriesMenuModel.
        /// </summary>
        public static string AltoCategoriesMenuModel {
            get {
                return ResourceManager.GetString("AltoCategoriesMenuModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to altoCategoryModel:{0}.
        /// </summary>
        public static string AltoCategoryModel {
            get {
                return ResourceManager.GetString("AltoCategoryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to benefitModel:{0}.
        /// </summary>
        public static string BenefitModel {
            get {
                return ResourceManager.GetString("BenefitModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blogPost:{0}.
        /// </summary>
        public static string BlogPost {
            get {
                return ResourceManager.GetString("BlogPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to feed:{0}.
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homeModel.
        /// </summary>
        public static string HomeModel {
            get {
                return ResourceManager.GetString("HomeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homeModelMobile.
        /// </summary>
        public static string HomeModelMobile {
            get {
                return ResourceManager.GetString("HomeModelMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homeStoryFeed.
        /// </summary>
        public static string HomeStoryFeed {
            get {
                return ResourceManager.GetString("HomeStoryFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to latestStoryPerCategory.
        /// </summary>
        public static string LatestStoriesPerCategory {
            get {
                return ResourceManager.GetString("LatestStoriesPerCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productmodelNew:{0}.
        /// </summary>
        public static string NewProductModel {
            get {
                return ResourceManager.GetString("NewProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newUserHomeModel.
        /// </summary>
        public static string NewUserHomeModel {
            get {
                return ResourceManager.GetString("NewUserHomeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications:{0}.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productmodel:{0}.
        /// </summary>
        public static string ProductModel {
            get {
                return ResourceManager.GetString("ProductModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productOfTheDay.
        /// </summary>
        public static string ProductOfTheDay {
            get {
                return ResourceManager.GetString("ProductOfTheDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serviceProvider:{0}.
        /// </summary>
        public static string ServiceProviderModel {
            get {
                return ResourceManager.GetString("ServiceProviderModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shopHomeModel.
        /// </summary>
        public static string ShopHomeModel {
            get {
                return ResourceManager.GetString("ShopHomeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to story:{0}.
        /// </summary>
        public static string StoryModel {
            get {
                return ResourceManager.GetString("StoryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to views.
        /// </summary>
        public static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
