using Serilog;
using System.Collections.Generic;

namespace Yooocan.Logic.Utils
{
    public class CountryHelper
    {
        private static Dictionary<string, string> _namesToCodes = new Dictionary<string, string>
        {
          {"andorra", "AD"},
{"united arab emirates", "AE"},
{"afghanistan", "AF"},
{"antigua and barbuda", "AG"},
{"anguilla", "AI"},
{"albania", "AL"},
{"armenia", "AM"},
{"angola", "AO"},
{"antarctica", "AQ"},
{"argentina", "AR"},
{"american samoa", "AS"},
{"austria", "AT"},
{"australia", "AU"},
{"aruba", "AW"},
{"åland islands", "AX"},
{"azerbaijan", "AZ"},
{"bosnia and herzegovina", "BA"},
{"barbados", "BB"},
{"bangladesh", "BD"},
{"belgium", "BE"},
{"burkina faso", "BF"},
{"bulgaria", "BG"},
{"bahrain", "BH"},
{"burundi", "BI"},
{"benin", "BJ"},
{"saint barthélemy", "BL"},
{"bermuda", "BM"},
{"brunei darussalam", "BN"},
{"brunei", "BN"},
{"bolivia, plurinational state of", "BO"},
{"bolivia", "BO"},
{"bonaire, sint eustatius and saba", "BQ"},
{"bonaire", "BQ"},
{"brazil", "BR"},
{"bahamas", "BS"},
{"bhutan", "BT"},
{"bouvet island", "BV"},
{"botswana", "BW"},
{"belarus", "BY"},
{"belize", "BZ"},
{"canada", "CA"},
{"cocos (keeling) islands", "CC"},
{"congo, the democratic republic of the", "CD"},
{"the democratic republic of the congo", "CD"},
{"central african republic", "CF"},
{"congo", "CG"},
{"republic of the congo", "CG"},
{"switzerland", "CH"},
{"côte d'ivoire", "CI"},
{"ivory coast", "CI"},
{"cook islands", "CK"},
{"chile", "CL"},
{"cameroon", "CM"},
{"china", "CN"},
{"colombia", "CO"},
{"costa rica", "CR"},
{"cuba", "CU"},
{"cabo verde", "CV"},
{"curaçao", "CW"},
{"christmas island", "CX"},
{"cyprus", "CY"},
{"czechia", "CZ"},
{"czech republic", "CZ"},
{"germany", "DE"},
{"djibouti", "DJ"},
{"denmark", "DK"},
{"dominica", "DM"},
{"dominican republic", "DO"},
{"algeria", "DZ"},
{"ecuador", "EC"},
{"estonia", "EE"},
{"egypt", "EG"},
{"western sahara", "EH"},
{"eritrea", "ER"},
{"spain", "ES"},
{"ethiopia", "ET"},
{"finland", "FI"},
{"fiji", "FJ"},
{"falkland islands (malvinas)", "FK"},
{"falkland islands", "FK"},
{"micronesia, federated states of", "FM"},
{"faroe islands", "FO"},
{"france", "FR"},
{"gabon", "GA"},
{"united kingdom of great britain and northern ireland", "GB"},
{"united kingdom", "GB"},
{"grenada", "GD"},
{"georgia", "GE"},
{"french guiana", "GF"},
{"guernsey", "GG"},
{"ghana", "GH"},
{"gibraltar", "GI"},
{"greenland", "GL"},
{"gambia", "GM"},
{"guinea", "GN"},
{"guadeloupe", "GP"},
{"equatorial guinea", "GQ"},
{"greece", "GR"},
{"south georgia and the south sandwich islands", "GS"},
{"guatemala", "GT"},
{"guam", "GU"},
{"guinea-bissau", "GW"},
{"guyana", "GY"},
{"hong kong", "HK"},
{"heard island and mcdonald islands", "HM"},
{"honduras", "HN"},
{"croatia", "HR"},
{"haiti", "HT"},
{"hungary", "HU"},
{"indonesia", "ID"},
{"ireland", "IE"},
{"israel", "IL"},
{"isle of man", "IM"},
{"india", "IN"},
{"british indian ocean territory", "IO"},
{"iraq", "IQ"},
{"iran, islamic republic of", "IR"},
{"iran", "IR"},
{"iceland", "IS"},
{"italy", "IT"},
{"jersey", "JE"},
{"jamaica", "JM"},
{"jordan", "JO"},
{"japan", "JP"},
{"kenya", "KE"},
{"kyrgyzstan", "KG"},
{"cambodia", "KH"},
{"kiribati", "KI"},
{"comoros", "KM"},
{"saint kitts and nevis", "KN"},
{"korea, democratic people's republic of", "KP"},
{"north korea", "KP"},
{"korea, republic of", "KR"},
{"south korea", "KR"},
{"kuwait", "KW"},
{"cayman islands", "KY"},
{"kazakhstan", "KZ"},
{"lao people's democratic republic", "LA"},
{"lebanon", "LB"},
{"saint lucia", "LC"},
{"liechtenstein", "LI"},
{"sri lanka", "LK"},
{"liberia", "LR"},
{"lesotho", "LS"},
{"lithuania", "LT"},
{"luxembourg", "LU"},
{"latvia", "LV"},
{"libya", "LY"},
{"morocco", "MA"},
{"monaco", "MC"},
{"moldova, republic of", "MD"},
{"moldova", "MD"},
{"montenegro", "ME"},
{"saint martin (french part)", "MF"},
{"madagascar", "MG"},
{"marshall islands", "MH"},
{"macedonia, the former yugoslav republic of", "MK"},
{"macedonia", "MK"},
{"mali", "ML"},
{"myanmar", "MM"},
{"mongolia", "MN"},
{"macao", "MO"},
{"northern mariana islands", "MP"},
{"martinique", "MQ"},
{"mauritania", "MR"},
{"montserrat", "MS"},
{"malta", "MT"},
{"mauritius", "MU"},
{"maldives", "MV"},
{"malawi", "MW"},
{"mexico", "MX"},
{"malaysia", "MY"},
{"mozambique", "MZ"},
{"namibia", "NA"},
{"new caledonia", "NC"},
{"niger", "NE"},
{"norfolk island", "NF"},
{"nigeria", "NG"},
{"nicaragua", "NI"},
{"netherlands", "NL"},
{"norway", "NO"},
{"nepal", "NP"},
{"nauru", "NR"},
{"niue", "NU"},
{"new zealand", "NZ"},
{"oman", "OM"},
{"panama", "PA"},
{"peru", "PE"},
{"french polynesia", "PF"},
{"papua new guinea", "PG"},
{"philippines", "PH"},
{"pakistan", "PK"},
{"poland", "PL"},
{"saint pierre and miquelon", "PM"},
{"pitcairn", "PN"},
{"puerto rico", "PR"},
{"palestine, state of", "PS"},
{"portugal", "PT"},
{"palau", "PW"},
{"paraguay", "PY"},
{"qatar", "QA"},
{"réunion", "RE"},
{"romania", "RO"},
{"serbia", "RS"},
{"russian federation", "RU"},
{"russia", "RU"},
{"rwanda", "RW"},
{"saudi arabia", "SA"},
{"solomon islands", "SB"},
{"seychelles", "SC"},
{"sudan", "SD"},
{"sweden", "SE"},
{"singapore", "SG"},
{"saint helena, ascension and tristan da cunha", "SH"},
{"slovenia", "SI"},
{"svalbard and jan mayen", "SJ"},
{"slovakia", "SK"},
{"sierra leone", "SL"},
{"san marino", "SM"},
{"senegal", "SN"},
{"somalia", "SO"},
{"suriname", "SR"},
{"south sudan", "SS"},
{"sao tome and principe", "ST"},
{"el salvador", "SV"},
{"sint maarten (dutch part)", "SX"},
{"syrian arab republic", "SY"},
{"syria", "SY"},
{"swaziland", "SZ"},
{"turks and caicos islands", "TC"},
{"chad", "TD"},
{"french southern territories", "TF"},
{"togo", "TG"},
{"thailand", "TH"},
{"tajikistan", "TJ"},
{"tokelau", "TK"},
{"timor-leste", "TL"},
{"turkmenistan", "TM"},
{"tunisia", "TN"},
{"tonga", "TO"},
{"turkey", "TR"},
{"trinidad and tobago", "TT"},
{"tuvalu", "TV"},
{"taiwan, province of china", "TW"},
{"taiwan", "TW"},
{"tanzania, united republic of", "TZ"},
{"tanzania", "TZ"},
{"ukraine", "UA"},
{"uganda", "UG"},
{"united states minor outlying islands", "UM"},
{"united states of america", "US"},
{"united states", "US"},
{"uruguay", "UY"},
{"uzbekistan", "UZ"},
{"holy see", "VA"},
{"saint vincent and the grenadines", "VC"},
{"venezuela, bolivarian republic of", "VE"},
{"venezuela", "VE"},
{"virgin islands, british", "VG"},
{"virgin islands, u.s.", "VI"},
{"viet nam", "VN"},
{"vietnam", "VN"},
{"vanuatu", "VU"},
{"wallis and futuna", "WF"},
{"samoa", "WS"},
{"yemen", "YE"},
{"mayotte", "YT"},
{"south africa", "ZA"},
{"zambia", "ZM"},
{"zimbabwe", "ZW"}
        };

        public static string ConvertToCountryCode(string countryName)
        {
            countryName = countryName.ToLower();
            if(_namesToCodes.ContainsKey(countryName))
            {
                return _namesToCodes[countryName];
            }
            Log.Warning("unable to find country code for {country}, it probably needs to be added to the list", countryName);
            return null;
        }
    }
}
