// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using Yooocan.Dal;
using Yooocan.Entities;
using Yooocan.Enums;
using Yooocan.Enums.Company;
using Yooocan.Enums.Notifications;
using Yooocan.Enums.Vendors;

namespace Yooocan.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171219153545_AddProductAltoIdIndexMig")]
    partial class AddProductAltoIdIndexMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Yooocan.Entities.AltoCategoryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<string>("CdnUrl");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("AltoCategoryImages");
                });

            modelBuilder.Entity("Yooocan.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutMe");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("City");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Country");

                    b.Property<bool>("CustomizedFeedDone");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FacebookPageUrl");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100);

                    b.Property<int?>("Gender");

                    b.Property<string>("HeaderImageUrl");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("InstagramUserName");

                    b.Property<string>("LastName")
                        .HasMaxLength(100);

                    b.Property<double?>("Latitude");

                    b.Property<string>("Location");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<double?>("Longitude");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("PostalCode");

                    b.Property<string>("SecurityStamp");

                    b.Property<string>("State");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Yooocan.Entities.Benefits.Benefit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompanyId");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<decimal?>("Discount");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("Yooocan.Entities.Benefits.BenefitCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BenefitId");

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BenefitCategories");
                });

            modelBuilder.Entity("Yooocan.Entities.Benefits.BenefitImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BenefitId");

                    b.Property<string>("CdnUrl");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("Order");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.ToTable("BenefitImages");
                });

            modelBuilder.Entity("Yooocan.Entities.Blog.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("Description");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<DateTime?>("PublishDate");

                    b.Property<string>("Title");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Yooocan.Entities.Blog.PostImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Order");

                    b.Property<int>("PostId");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("PostImages");
                });

            modelBuilder.Entity("Yooocan.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<int>("FollowersCount");

                    b.Property<string>("HeaderPictureUrl");

                    b.Property<bool>("IsActiveForFeed");

                    b.Property<bool>("IsActiveForShop");

                    b.Property<bool>("IsChoosableForProduct");

                    b.Property<bool>("IsChoosableForStory");

                    b.Property<string>("MenuIconUrl");

                    b.Property<string>("MobileHeaderPictureUrl");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentCategoryId");

                    b.Property<string>("PictureUrl");

                    b.Property<int?>("RedirectCategoryId");

                    b.Property<string>("RoundIcon");

                    b.Property<string>("ShopBackgroundColor")
                        .IsRequired()
                        .HasColumnType("CHAR(6)");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("RedirectCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Yooocan.Entities.CategoryFollower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "CategoryId", "DeleteDate");

                    b.ToTable("CategoryFollowers");
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.AltoCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsHeader");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("AltoCategories");
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<string>("Address");

                    b.Property<int>("BusinessType");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<int?>("DiscountRateType");

                    b.Property<string>("FaxNumber");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsForeignCurrency");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<decimal?>("MembersDiscountRate");

                    b.Property<string>("Name");

                    b.Property<string>("OnBoardingContactPersonEmail");

                    b.Property<DateTime?>("OnBoardingDate");

                    b.Property<string>("OtherRequestedCategories");

                    b.Property<decimal?>("ReferralRate");

                    b.Property<int?>("ReferralRateType");

                    b.Property<string>("ReferrerFormat");

                    b.Property<string>("TelephoneNumber");

                    b.Property<string>("TollFreeNumber");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<int>("CompanyId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyCategory");
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyContactPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<string>("Email");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneExtension");

                    b.Property<string>("Position");

                    b.Property<string>("Skype");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyContactPersons");
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyCoupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Code");

                    b.Property<int>("CompanyId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<int?>("UsesLeft");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyCoupons");
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CdnUrl");

                    b.Property<int>("CompanyId");

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyImages");
                });

            modelBuilder.Entity("Yooocan.Entities.FeaturedStory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("FeaturedType");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("StoryId");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("FeaturedStories");
                });

            modelBuilder.Entity("Yooocan.Entities.Feed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Location");

                    b.Property<int?>("ParentCategoryId");

                    b.Property<string>("PrimaryImageUrl");

                    b.Property<int>("SubCategoryId");

                    b.Property<string>("SubCategoryName");

                    b.Property<string>("Title");

                    b.Property<string>("UserImageUrl");

                    b.HasKey("Id");

                    b.ToTable("Feed");
                });

            modelBuilder.Entity("Yooocan.Entities.FileUpload", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsUsed");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("FileUploads");
                });

            modelBuilder.Entity("Yooocan.Entities.FollowerFollowed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FollowedUserId")
                        .IsRequired();

                    b.Property<string>("FollowerUserId")
                        .IsRequired();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.HasIndex("FollowedUserId");

                    b.HasIndex("FollowerUserId");

                    b.ToTable("Followers");
                });

            modelBuilder.Entity("Yooocan.Entities.Limitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Name");

                    b.Property<int?>("ParentLimitationId");

                    b.HasKey("Id");

                    b.HasIndex("ParentLimitationId");

                    b.ToTable("Limitations");
                });

            modelBuilder.Entity("Yooocan.Entities.LimitationFollower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("LimitationId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LimitationId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "LimitationId", "DeleteDate");

                    b.ToTable("LimitationFollowers");
                });

            modelBuilder.Entity("Yooocan.Entities.NewsletterSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("IpAddress");

                    b.Property<bool>("IsVerified");

                    b.Property<bool>("Unsubscribed");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NewsletterSubscribers");
                });

            modelBuilder.Entity("Yooocan.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ImageUrl");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Link");

                    b.Property<int?>("ObjectId");

                    b.Property<int?>("ParentId");

                    b.Property<int?>("ParentType");

                    b.Property<string>("SourceUserId");

                    b.Property<string>("Text");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("SourceUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Yooocan.Entities.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsSuccess");

                    b.Property<string>("Method");

                    b.Property<string>("NotificationId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("Yooocan.Entities.NotificationRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("NotificationId");

                    b.Property<DateTime?>("ReadDate");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("NotificationRecipients");
                });

            modelBuilder.Entity("Yooocan.Entities.PendingClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("CreatedById")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(254);

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<bool>("WasAssigned");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("PendingClaims");
                });

            modelBuilder.Entity("Yooocan.Entities.PrivateMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content");

                    b.Property<string>("FromUserId")
                        .IsRequired();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeletedByRecipient");

                    b.Property<bool>("IsDeletedBySender");

                    b.Property<DateTime?>("ReadDate");

                    b.Property<string>("Title")
                        .HasMaxLength(254);

                    b.Property<string>("ToUserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("PrivateMessages");
                });

            modelBuilder.Entity("Yooocan.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<int?>("AltoId");

                    b.Property<string>("AmazonId");

                    b.Property<string>("Brand");

                    b.Property<string>("Colors");

                    b.Property<int?>("CompanyId");

                    b.Property<string>("CouponCode");

                    b.Property<bool>("CouponNotNeeded");

                    b.Property<float?>("Depth");

                    b.Property<decimal?>("DiscountRate");

                    b.Property<int?>("DiscountType");

                    b.Property<float?>("Height");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.Property<bool>("IsSoldOnSite");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<decimal?>("ListPrice");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<string>("RedirectPageComment");

                    b.Property<string>("Sku");

                    b.Property<string>("Specifications");

                    b.Property<string>("Upc");

                    b.Property<string>("Url");

                    b.Property<int?>("VendorId");

                    b.Property<string>("VideoUrl");

                    b.Property<string>("WarrentyUrl");

                    b.Property<float?>("Weight");

                    b.Property<float?>("Width");

                    b.Property<string>("YouTubeId");

                    b.HasKey("Id");

                    b.HasIndex("AltoId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("VendorId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Yooocan.Entities.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CategoryId");

                    b.Property<bool>("IsMain");

                    b.Property<int>("ProductId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CategoryId", "ProductId")
                        .IsUnique();

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("Yooocan.Entities.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CdnUrl");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Order");

                    b.Property<string>("OriginalUrl");

                    b.Property<int>("ProductId");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("Yooocan.Entities.ProductLimitation", b =>
                {
                    b.Property<int>("LimitationId");

                    b.Property<int>("ProductId");

                    b.HasKey("LimitationId", "ProductId");

                    b.HasIndex("LimitationId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductLimitations");
                });

            modelBuilder.Entity("Yooocan.Entities.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("ProductId");

                    b.Property<byte>("Rating");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Yooocan.Entities.Products.CompanyShipping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CompanyId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<decimal>("MaxProductPrice");

                    b.Property<int?>("MaxShippingDuration");

                    b.Property<decimal>("MinProductPrice");

                    b.Property<int?>("MinShippingDuration");

                    b.Property<string>("ShippingMethod");

                    b.Property<decimal>("ShippingPrice");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyShippings");
                });

            modelBuilder.Entity("Yooocan.Entities.ReadHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CategoryId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int?>("StoryId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "InsertDate", "CategoryId", "StoryId");

                    b.ToTable("ReadHistories");
                });

            modelBuilder.Entity("Yooocan.Entities.Referrals.BenefitReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BenefitId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Ip");

                    b.Property<string>("Referrer");

                    b.Property<string>("Url");

                    b.Property<string>("UserAgent");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("BenefitId");

                    b.HasIndex("UserId");

                    b.ToTable("BenefitReferrals");
                });

            modelBuilder.Entity("Yooocan.Entities.Referrals.ProductReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Ip")
                        .IsRequired();

                    b.Property<int>("ProductId");

                    b.Property<string>("Referrer");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.Property<string>("UserAgent")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReferrals");
                });

            modelBuilder.Entity("Yooocan.Entities.Referrals.ServiceProviderReferral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Ip")
                        .IsRequired();

                    b.Property<string>("Referrer");

                    b.Property<int>("ServiceProviderId");

                    b.Property<string>("Url")
                        .IsRequired();

                    b.Property<string>("UserAgent")
                        .IsRequired();

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceProviderReferrals");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutTheCompany");

                    b.Property<string>("AdditionalInformation");

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("ContactPresonName");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("Facebook");

                    b.Property<string>("FaxNumber");

                    b.Property<string>("HeaderImageUrl");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Instagram");

                    b.Property<bool>("IsChapter");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<double?>("Latitude");

                    b.Property<string>("LogoUrl");

                    b.Property<double?>("Longitude");

                    b.Property<string>("MobileNumber");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.Property<string>("StreetName");

                    b.Property<string>("StreetNumber");

                    b.Property<string>("TollFreePhoneNumber");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("Id");

                    b.ToTable("ServiceProviders");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("OpenDays");

                    b.Property<int>("Order");

                    b.Property<decimal>("Price");

                    b.Property<int?>("ServiceProviderId");

                    b.Property<string>("Units");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderActivities");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderCategory", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<int>("ServiceProviderId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("CategoryId", "ServiceProviderId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderCategories");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Email");

                    b.Property<string>("Message");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("ServiceProviderId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderContactRequests");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderFollower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<int>("ServiceProviderId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceProviderFollowers");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CdnUrl");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPrimaryImage");

                    b.Property<int>("Order");

                    b.Property<int>("ServiceProviderId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderImages");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderLimitation", b =>
                {
                    b.Property<int>("LimitationId");

                    b.Property<int>("ServiceProviderId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("LimitationId", "ServiceProviderId");

                    b.HasIndex("LimitationId");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderLimitations");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPrimaryVideo");

                    b.Property<int>("Order");

                    b.Property<int>("ServiceProviderId");

                    b.Property<string>("YouTubeId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.ToTable("ServiceProviderVideos");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.StoryServiceProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Order");

                    b.Property<int>("ServiceProviderId");

                    b.Property<int>("StoryId");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProviderId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryServiceProviders");
                });

            modelBuilder.Entity("Yooocan.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActivityLocation");

                    b.Property<bool>("CanNotBeFeaturedOnHomePage");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("GooglePlaceId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsInCompetition");

                    b.Property<bool>("IsNoIndex");

                    b.Property<bool>("IsProductsReviewed");

                    b.Property<bool>("IsPublished");

                    b.Property<DateTime>("LastUpdateDate");

                    b.Property<double?>("Latitude");

                    b.Property<int>("LikesCount");

                    b.Property<double?>("Longitude");

                    b.Property<string>("PostalCode");

                    b.Property<DateTime?>("PublishDate");

                    b.Property<string>("Quote");

                    b.Property<string>("State");

                    b.Property<string>("StreetName");

                    b.Property<string>("StreetNumber");

                    b.Property<string>("Title");

                    b.Property<string>("UsedProducts");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<int>("ViewsCount");

                    b.Property<string>("YouTubeId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Id", "PublishDate", "IsPublished");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryCategory", b =>
                {
                    b.Property<int>("CategoryId");

                    b.Property<int>("StoryId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPrimary");

                    b.HasKey("CategoryId", "StoryId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryCategories");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("StoryId");

                    b.Property<string>("Text");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("StoryComments");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CdnUrl");

                    b.Property<float?>("HotAreaLeft");

                    b.Property<float?>("HotAreaTop");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Order");

                    b.Property<int>("StoryId");

                    b.Property<int>("Type");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryImages");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("DeleteDate");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("StoryId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.HasIndex("UserId");

                    b.ToTable("StoryLikes");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryLimitation", b =>
                {
                    b.Property<int>("LimitationId");

                    b.Property<int>("StoryId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPrimary");

                    b.HasKey("LimitationId", "StoryId");

                    b.HasIndex("LimitationId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryLimitations");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryParagraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Order");

                    b.Property<int>("StoryId");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryParagraphs");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryProduct", b =>
                {
                    b.Property<int>("StoryId");

                    b.Property<int>("ProductId");

                    b.Property<bool>("IsUsedInStory");

                    b.Property<int>("Order");

                    b.HasKey("StoryId", "ProductId");

                    b.HasIndex("ProductId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryProducts");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<bool>("IsDeleted");

                    b.Property<int>("Order");

                    b.Property<int>("StoryId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryTips");
                });

            modelBuilder.Entity("Yooocan.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("About");

                    b.Property<int?>("AltoId");

                    b.Property<int>("BusinessType");

                    b.Property<string>("BusinessTypeOther");

                    b.Property<string>("City");

                    b.Property<int?>("CommercialTerms");

                    b.Property<string>("CommercialTermsOther");

                    b.Property<decimal?>("CommercialTermsRate");

                    b.Property<string>("CompanyCode");

                    b.Property<string>("ContactPersonEmail");

                    b.Property<string>("ContactPersonName");

                    b.Property<string>("ContactPersonPhoneNumber");

                    b.Property<string>("ContactPersonPosition");

                    b.Property<string>("ContactPersonSkype");

                    b.Property<string>("Country");

                    b.Property<string>("Facebook");

                    b.Property<string>("FaxNumber");

                    b.Property<string>("GooglePlaceId");

                    b.Property<DateTime>("InsertDate")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("GetUtcDate()");

                    b.Property<string>("Instagram");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastUpdateDate");

                    b.Property<double?>("Latitude");

                    b.Property<string>("LocationText");

                    b.Property<string>("LogoUrl");

                    b.Property<double?>("Longitude");

                    b.Property<string>("Name");

                    b.Property<string>("OnBoardingContactPersonEmail");

                    b.Property<DateTime?>("OnBoardingDate");

                    b.Property<string>("PostalCode");

                    b.Property<string>("State");

                    b.Property<string>("StreetName");

                    b.Property<string>("StreetNumber");

                    b.Property<string>("TelephoneNumber");

                    b.Property<string>("TollFreeNumber");

                    b.Property<string>("Twitter");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("Yooocan.Entities.VendorRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BusinessType");

                    b.Property<string>("BusinessTypeOther");

                    b.Property<string>("ContactPresonName");

                    b.Property<string>("ContactPresonRole");

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("WasHandled");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("Id");

                    b.ToTable("VendorRegistrations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.AltoCategoryImage", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.AltoCategory", "Category")
                        .WithMany("Images")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.Benefits.Benefit", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.Company", "Company")
                        .WithMany("Benefits")
                        .HasForeignKey("CompanyId");
                });

            modelBuilder.Entity("Yooocan.Entities.Benefits.BenefitCategory", b =>
                {
                    b.HasOne("Yooocan.Entities.Benefits.Benefit", "Benefit")
                        .WithMany("Categories")
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Yooocan.Entities.Companies.AltoCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.Benefits.BenefitImage", b =>
                {
                    b.HasOne("Yooocan.Entities.Benefits.Benefit")
                        .WithMany("Images")
                        .HasForeignKey("BenefitId");
                });

            modelBuilder.Entity("Yooocan.Entities.Blog.Post", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Yooocan.Entities.Blog.PostImage", b =>
                {
                    b.HasOne("Yooocan.Entities.Blog.Post")
                        .WithMany("Images")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.Category", b =>
                {
                    b.HasOne("Yooocan.Entities.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.HasOne("Yooocan.Entities.Category", "RedirectCategory")
                        .WithMany()
                        .HasForeignKey("RedirectCategoryId");
                });

            modelBuilder.Entity("Yooocan.Entities.CategoryFollower", b =>
                {
                    b.HasOne("Yooocan.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany("Categories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.AltoCategory", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.AltoCategory", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyCategory", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.AltoCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.Companies.Company", "Company")
                        .WithMany("Categories")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyContactPerson", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.Company", "Company")
                        .WithMany("ContactPersons")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyCoupon", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.Company", "Company")
                        .WithMany("Coupons")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Companies.CompanyImage", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.Company", "Company")
                        .WithMany("Images")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.FeaturedStory", b =>
                {
                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.FollowerFollowed", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "FollowedUser")
                        .WithMany("Followers")
                        .HasForeignKey("FollowedUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "FollowerUser")
                        .WithMany("Follows")
                        .HasForeignKey("FollowerUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Limitation", b =>
                {
                    b.HasOne("Yooocan.Entities.Limitation", "ParentLimitation")
                        .WithMany()
                        .HasForeignKey("ParentLimitationId");
                });

            modelBuilder.Entity("Yooocan.Entities.LimitationFollower", b =>
                {
                    b.HasOne("Yooocan.Entities.Limitation", "Limitation")
                        .WithMany()
                        .HasForeignKey("LimitationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany("Limitations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Notification", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "SourceUser")
                        .WithMany()
                        .HasForeignKey("SourceUserId");
                });

            modelBuilder.Entity("Yooocan.Entities.NotificationLog", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.NotificationRecipient", b =>
                {
                    b.HasOne("Yooocan.Entities.Notification", "Notification")
                        .WithMany("Recipients")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.PendingClaim", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.PrivateMessage", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Product", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.Company", "Company")
                        .WithMany("Products")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Yooocan.Entities.Vendor", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorId");
                });

            modelBuilder.Entity("Yooocan.Entities.ProductCategory", b =>
                {
                    b.HasOne("Yooocan.Entities.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ProductImage", b =>
                {
                    b.HasOne("Yooocan.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ProductLimitation", b =>
                {
                    b.HasOne("Yooocan.Entities.Limitation", "Limitation")
                        .WithMany()
                        .HasForeignKey("LimitationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.Product", "Product")
                        .WithMany("ProductLimitations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ProductReview", b =>
                {
                    b.HasOne("Yooocan.Entities.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany("ProductReviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Products.CompanyShipping", b =>
                {
                    b.HasOne("Yooocan.Entities.Companies.Company", "Company")
                        .WithMany("ShippingRules")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.ReadHistory", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.Referrals.BenefitReferral", b =>
                {
                    b.HasOne("Yooocan.Entities.Benefits.Benefit", "Benefit")
                        .WithMany()
                        .HasForeignKey("BenefitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Yooocan.Entities.Referrals.ProductReferral", b =>
                {
                    b.HasOne("Yooocan.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Yooocan.Entities.Referrals.ServiceProviderReferral", b =>
                {
                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "Product")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderActivity", b =>
                {
                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany("Activities")
                        .HasForeignKey("ServiceProviderId");
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderCategory", b =>
                {
                    b.HasOne("Yooocan.Entities.Category", "Category")
                        .WithMany("ServiceProviderCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany("ServiceProviderCategories")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderContactRequest", b =>
                {
                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany("ServiceProviderContactRequests")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderFollower", b =>
                {
                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderImage", b =>
                {
                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany("Images")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderLimitation", b =>
                {
                    b.HasOne("Yooocan.Entities.Limitation", "Limitation")
                        .WithMany()
                        .HasForeignKey("LimitationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany("ServiceProviderLimitations")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.ServiceProviderVideo", b =>
                {
                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany("Videos")
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.ServiceProviders.StoryServiceProvider", b =>
                {
                    b.HasOne("Yooocan.Entities.ServiceProviders.ServiceProvider", "ServiceProvider")
                        .WithMany()
                        .HasForeignKey("ServiceProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("StoryServiceProviders")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.Story", b =>
                {
                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.StoryCategory", b =>
                {
                    b.HasOne("Yooocan.Entities.Category", "Category")
                        .WithMany("StoryCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("StoryCategories")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.StoryComment", b =>
                {
                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("Comments")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany("StoryComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Yooocan.Entities.StoryImage", b =>
                {
                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("Images")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.StoryLike", b =>
                {
                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany()
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Yooocan.Entities.StoryLimitation", b =>
                {
                    b.HasOne("Yooocan.Entities.Limitation", "Limitation")
                        .WithMany()
                        .HasForeignKey("LimitationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("StoryLimitations")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.StoryParagraph", b =>
                {
                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("Paragraphs")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.StoryProduct", b =>
                {
                    b.HasOne("Yooocan.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("StoryProducts")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Yooocan.Entities.StoryTip", b =>
                {
                    b.HasOne("Yooocan.Entities.Story", "Story")
                        .WithMany("Tips")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
