//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alto.Logic {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RedisKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal RedisKeys() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alto.Logic.RedisKeys", typeof(RedisKeys).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to benefitModel:{0}.
        /// </summary>
        public static string BenefitModel {
            get {
                return ResourceManager.GetString("BenefitModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to categoriesMenuModel.
        /// </summary>
        public static string CategoriesMenuModel {
            get {
                return ResourceManager.GetString("CategoriesMenuModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to categoryModel:{0}.
        /// </summary>
        public static string CategoryModel {
            get {
                return ResourceManager.GetString("CategoryModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to homeModel.
        /// </summary>
        public static string HomeModel {
            get {
                return ResourceManager.GetString("HomeModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to homeRandomModel.
        /// </summary>
        public static string HomeRandomModel {
            get {
                return ResourceManager.GetString("HomeRandomModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to productModel:{0}.
        /// </summary>
        public static string ProductModel {
            get {
                return ResourceManager.GetString("ProductModel", resourceCulture);
            }
        }
    }
}
